version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    ports:
      - "8082:8082"
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory

volumes:
  jenkins_home:
  artifactory_data:
